### ISSUE TITLE
Should we try to merge this stuff into the "upstream" / official Red Hat actions repo

### ISSUE THREAD

**Issue by springdo** [redhat-cop/github-actions#34]
https://github.com/redhat-actions is the new home for official actions. How much of the work here could be moved towards this official source for red hattishnes?

**Comment by garethahealy** [comment]
there was a bit of chatter on gchat around this, but from looking at whats currently in the repo, i'd only say the `s2i` action.

**Comment by garethahealy** [comment]
@springdo ; anything else need to be done on this? I've added a callout to the rh-actions for s2i in the readme.
- https://github.com/redhat-cop/github-actions/tree/master/s2i#use-redhat-actionss2i-build
