### ISSUE TITLE
github action for checking branch refs 

### ISSUE THREAD

**Issue by pcarney8** [redhat-cop/github-actions#4]
Similar to WIP action, but warns people about the fact that their branch ref might need to change on their merge.

Even better would be to _do_ the branch ref change on merge for people, but not sure that's possible

**Comment by garethahealy** [comment]
@pcarney8 ; not sure I understand the description. Are you saying:

`Someone raises a PR and their branch is set as "my-change" and because it doesn't match the branch it's being merged into, i.e.: master, warn them?`

or something else?

**Comment by garethahealy** [comment]
stale
